FROM python:3.11-slim AS builder
WORKDIR /app
RUN apt-get update && apt-get install -y binutils && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pyinstaller
COPY . .
RUN pyinstaller --onefile \
    --hidden-import=passlib.handlers.bcrypt \
    --hidden-import=passlib.handlers.sha2_crypt \
    --hidden-import=passlib.utils.pbkdf2 \
    --hidden-import=psycopg2 \
    --hidden-import=jose \
    --hidden-import=dotenv \
    main.py

FROM python:3.11
WORKDIR /app
COPY --from=builder /app/dist/main .
RUN chmod +x main
EXPOSE 8000
CMD ["./main"]